pangeo-data/pangeo-stacks

.travis.yml
base-notebook/binder/tests/test_env.py
base-notebook/binder/verify
pangeo-notebook/binder/tests/test_env.py
pangeo-notebook/binder/verify

Just jotting down some ideas from https://github.com/jupyter/repo2docker/issues/93
Do not merge.
cc @alando46

add verify script

---

appendix.txt

Otherwise they get put in $HOME, which causes problems
when you try to put persistent storage there.

Install nbextensions into sys.prefix

---

appendix.txt

This saves us some space and time. These wheels
will never be used anyway.

Don't cache wheels with pip install

---

.travis.yml
build.py
docker_push.sh
requirements.txt

- Pull the last built + pushed image before building
an image. We tell repo2docker to re-use docker
layers from the pulled image, speeding up our
build process.
- Switch to a python script for the building.

Cache previously built images to speed up builds

---

build.py
docker_push.sh
onbuild/Dockerfile
onbuild/r2d_overlay.py

This lets people use our images as a base, but
customize it easily with a subset of the files
understood by repo2docker. Currently, this includes:
- environment.yml
- requirements.txt
- postBuild
- apt.txt
We can add more if necessary.
The contents of the user's repository are also copied
into ${HOME}, merging with (and overwriting) anything
that's in our base images.
To use the onbuild images as a base,
1. In your git repository, create a file named 'Dockerfile'
2. Write the name of the base image you would like to use
in the following format:
'FROM <base-image>:<tag>'
For example, you can write:
'FROM pangeo/base-notebook-onbuild:2019.04.15'
Note the -onbuild - that is very important.
3. Create a 'environment.yml', 'requirements.txt' or
'postBuild' file in your repository (or under a …

Provide -onbuild variants of all images

---

.travis.yml
docker_push.sh

- Since we no longer matrix by image, we need to
pass the image name explicitly to the docker push
script
- Make bash fail on first error

Fix travis deploy step

---

pangeo-notebook/binder/environment.yml
pangeo-notebook/binder/tests/test_imports.py

Adds tensorflow, keras, and pytorch.
As long as #23 remains unresolved, we can't use the gpu-optimized versions of the libraries because they are not available on conda forge.

add deep learning packages

---

onbuild/Dockerfile

Some binders don't have a new enough version of the
docker daemon running, because they are using the same docker
as running in GKE. This version is pretty old, so
--chown is not supported. This works around that
by manually running chown. This increases image size, but
works universally.
See https://github.com/pangeo-data/pangeo-stacks/issues/36

Don't use --chown in onbuild variants

---

requirements.txt

This unpins repo2docker now that a few stable releases have passed.

unpin repo2docker

---

base-notebook/binder/dask_config.yaml
base-notebook/binder/environment.yml
base-notebook/binder/tests/test_dask_env.py
base-notebook/binder/tests/test_imports.py
onbuild/r2d_overlay.py
pangeo-notebook/binder/apt.txt

Repo2docker dask fixes

---

base-notebook/binder/environment.yml
base-notebook/binder/postBuild
base-notebook/binder/tests/test_imports.py
pangeo-notebook/binder/environment.yml

- python 3.6 -> 3.7
- jupyterlab -> 1.0.0
- tornado 5.1.1 -> 6.0.3

Bump Python, jlab, and tornado versions.

---

base-notebook/binder/environment.yml
base-notebook/binder/postBuild
base-notebook/binder/tests/test_imports.py

Closes https://github.com/pangeo-data/pangeo-stacks/issues/50
https://github.com/pangeo-data/pangeo-stacks/issues/50#issuecomment-513588318 (maybe fixes it).

Enable JupterLab=1: noasync dask labextension branch

---

base-notebook/binder/environment.yml
pangeo-notebook/binder/environment.yml

i'm hoping this fixes our woes with https://github.com/pangeo-data/pangeo-cloud-federation/pull/362 .
I think we need to start pinning packages that are known to be compatible (TBD for pangeo-notebook). As far as I can tell there are some version incompatibilities w/ newly built images with the ML packages `tensorflow` and `keras`. And pip installing `xrviz` is bringing along a dated version of `holoviews`. Let's see if this fixes things for now.

Pangeo notebook fix

---

pangeo-notebook/binder/environment.yml

Attempting to fix https://github.com/pangeo-data/pangeo-cloud-federation/issues/370 
In brief, we removed the ML libs because conda was giving errors such as 
`ERROR conda.core.link:_execute(637): An error occurred while installing package 'None'.
AssertionError()`
https://circleci.com/gh/pangeo-data/pangeo-cloud-federation/694
This was tricky to sort out, and I'm still not sure I understand what was going on, but at the time running repo2docker locally and removing the ML packages removed the error and allowed on-build variants on pangeo-cloud-federation to build. 
On one hand, the unpinned versions in pangeo-notebook should allow for compatible combinations. On the other, having many packages with complicated dependencies makes the environment hard to solve (or it seems prone to …

Return ml libs

---

pangeo-notebook/binder/environment.yml

This will make it easier for us to test out tiledb on pango cloud environments.
cc @normanb

add tiledb to notebook environment

---

onbuild/r2d_overlay.py

Steal code directly from repo2docker to match behavior:
https://github.com/jupyter/repo2docker/blob/4f428c305576ccf1f1ff1fb18b11bbf1402ca7bd/repo2docker/buildpacks/base.py#L478
Ref https://github.com/pangeo-data/pangeo-cmip6-examples/issues/7#issuecomment-532491546

Add support for .binder directories

---

docs/build_stacks_rst.py

The docker links are broken on the website:
https://pangeo-data.github.io/pangeo-stacks/images.html#pangeo-pangeo-notebook
They look like 
```
https://hub.docker.com/r/pangeo/pangeo/pangeo-notebook
```
This removes the duplicate pangeo.

fix dockerhub link

---

README.md

I believe this should point to the `onbuild` variety of this image for this to work, but I might also be misunderstanding.

DOC: Fixes README onbuild example

---

pangeo-esip/binder/environment.yml

I tagged `pangeo/pangeo-notebook:latest` as `pangeo/pangeo-esip:2019.11.20` to "seed" dockerhub since the CI expects a container to already exist.

Try with prepopulated esip container on dockerhub

---

base-notebook/binder/dask_config.yaml
base-notebook/binder/environment.yml

This adds a maximum worker pod lifetime of 5 hours, which is a solution to cases where dask pods get stuck in `Running` states:
https://github.com/pangeo-data/pangeo-cloud-federation/issues/408#issuecomment-555169379 
```
worker:
lifetime: "5 hours"
```
Do people think this is ok? Willing to wait and see if other solutions come up in the above issue.

bump dask to 2.8.1, add optional worker lifetime config

---

base-notebook/binder/dask_config.yaml

Temporary fix for https://github.com/pangeo-data/pangeo-cloud-federation/issues/485
@TomAugspurger @jhamman

dask pods get daskkubernetes sa instead of default

---

.travis.yml

The pangeo-notebook fails on/off to solve for the environment but the pangeo-esip does not. Let's deploy the latter first so we can help @rsignell-usgs get an image for his demo in January.
PS: I'm also checking why the pangeo-notebook is failing to solve in an acceptable amount of time. That is a conda problem regardless of the CI used here.

push ESIP first

---

onbuild/Dockerfile
onbuild/r2d_overlay.py

This PR may need some editing but gives some base code to allow those who build pangeo binders to use the base binder images as a starter AND use binder/start at the same time.

Add code to allow the use of binder/start

---

requirements.txt

Try rebuilding images with latest release of repo2docker now on pypi https://github.com/jupyter/repo2docker/releases

repo2docker 0.11 up from 0.10

---

base-notebook/binder/dask_config.yaml

fixes error for users creating clusters with underscore characters in their github user name or binder repositories with underscores:
https://github.com/dask/dask-kubernetes/issues/230

fix dask container name

---

onbuild/Dockerfile
pangeo-notebook/binder/start
pangeo-notebook/binder/tests/test_start.py

seems like this line got removed by accident in PR related to implementing the `start` sidecar file.
hopefully fixes https://github.com/pangeo-data/pangeo-stacks/issues/134 
@rabernat, @yuvipanda, @tjcrone

Fix onbuild images to prevent resolving environment when launched with binder

---

onbuild/r2d_overlay.py
pangeo-notebook/binder/start
pangeo-notebook/binder/tests/test_start.py

last PR was unsuccessful in enabling start script. https://github.com/pangeo-data/pangeo-stacks/pull/135 
the test passed b/c the environment variable in the start script didn't get set and the value therefore wasn't actually checked. I'm hopeful this will fix it.

try to fix start script

---

base-notebook/binder/environment.yml

fixes errors due to compatibility with msgpack 1.0 (https://github.com/dask/distributed/pull/3494)

bump dask and distributed to 2.11
