- appendix.txt
- pangeo-notebook/binder/environment.yml
- pangeo-notebook/binder/postBuild
closes #5 
fixes #4 
resolves #3
> add dask lab extension and cartopy to pangeo-notebook

- README.md
I find these extra badges from microbadger very useful. Thought I would add them here.
> Add more docker badges

- .travis.yml
Ridiculous, since the build step acceps a list
> Travis deploy only accepts a single command

- .travis.yml
> try out multiple deploy blocks in travis.yml

- README.md
> Document where repo contents are copied into

- base-notebook/binder/environment.yml
- pangeo-notebook/binder/environment.yml
closes #42. Need to wait on the tests for this one...
> unpin versions in base and pangeo notebooks

- base-notebook/binder/environment.yml
- pangeo-notebook/binder/environment.yml
Similar to https://github.com/pangeo-data/pangeo-cloud-federation/pull/305
> avoid pip packages

- README.md
appendix is no longer used, right?
> remove appendix from local build instructions

- base-notebook/binder/dask_config.yaml
- base-notebook/binder/environment.yml
Not sure when we'll want to merge this, but putting it up before I forget.
> Update to dask / distributed 2.x

- pangeo-notebook/binder/environment.yml
- bumps xarray to 0.12.2
- adds xrviz to image
> [pangeo-notebook] Version bump

- requirements.txt
> Repo2docker bump

- base-notebook/binder/environment.yml
- base-notebook/binder/postBuild
- base-notebook/binder/tests/test_imports.py
- pangeo-notebook/binder/tests/test_imports.py
> add jhub/nbgitpuller to baseimage

- base-notebook/binder/environment.yml
- base-notebook/binder/postBuild
- pangeo-notebook/binder/environment.yml
I'm prepping for the cmip6 hack next week. This is the first round of version bumps. 
cc @andersy005 @rabernat
> bump versions

- base-notebook/binder/environment.yml
- base-notebook/binder/postBuild
- base-notebook/binder/tests/test_imports.py
> bumped versions

- base-notebook/binder/environment.yml
- pangeo-notebook/binder/apt.txt
- pangeo-notebook/binder/environment.yml
> base version bump, rebuild pangeo-notebook

- base-notebook/binder/dask_config.yaml
Not sure what in dask / distributed changed, but this fixes
it for me locally.
Closes https://github.com/pangeo-data/pangeo-stacks/issues/91
> Specify logging at the top-level

- pangeo-esip/binder/Dockerfile
- pangeo-esip/binder/apt.txt
- pangeo-esip/binder/environment.yml
- pangeo-esip/binder/postBuild
- pangeo-esip/binder/verify
@scottyhq suggested I add the ESIP environment here so we can point to on the profile list on deployments like: https://github.com/pangeo-data/pangeo-cloud-federation/blob/staging/deployments/icesat2/config/common.yaml#L87
Please check, as it's my first time trying this and likely got some minor thing wrong.
> added esip env

- base-notebook/binder/environment.yml
- pangeo-notebook/binder/environment.yml
> bump base versions

- base-notebook/binder/environment.yml
- pangeo-notebook/binder/environment.yml
> bump dask, add a few more packages to pangeo-notebook

- .travis.yml
- pangeo-esip/binder/apt.txt
- pangeo-esip/binder/environment.yml
Revival of #98 b/c this solves the ESIP image build.
Ping @rsignell-usgs.
> matrix and remove apt installs

- .github/workflows/master.yml
- base-notebook/binder/environment.yml
most recent base notebook package versions as of feb 2020
> bumped base-notebook versions

- .github/workflows/master.yml
- .github/workflows/pull_request.yml
- build.py
- requirements.txt
fixing current MasterBuild CI error:
```
docker: Error response from daemon: pull access denied for conda, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
1736
See 'docker run --help'.
1737
##[error]Process completed with exit code 125.
```
this PR also refactors build.py to try to utilize docker build --cache-from except for pangeo-ml image which is too big to pre-pull currently for CI disk limits
> fix MasterBuild CI
